### ISSUE TITLE
docChanges() does not include `removed` items

### ISSUE THREAD

**Issue by wSedlacek** [gustavohenke/mockbase#18]
First I would like to thank you Gustavo for all the hard work you have put into mocking Firebase.
I have been attempting to build out proper unit test when using Angular Fire and your mock of Firebase has been instrumental in building out proper mocks.

I am running into an issue with your mock of Firestore though. That is that it is only sending me the `added` docs but not `removed` or `modified`.

This is the section of code that I am getting stuck and and not getting past the short circuit. 
https://github.com/gustavohenke/mockbase/blob/e271ba2304d24133a677a0bd459df222d1b4edac/firestore/query-snapshot.ts#L29-L37

This is where the `lastSnapshot` seems like it should be set to prevent that short circuit
https://github.com/gustavohenke/mockbase/blob/e271ba2304d24133a677a0bd459df222d1b4edac/firestore/query.ts#L41-L55

Code I am using
```ts
      const subject = new Subject();
      this.app
        .firestore()
        .collection(path)
        .onSnapshot({
          next: (collection) => {
            subject.next(
              collection.docChanges().map(({ type, doc }) => ({ type, payload: { doc } }))
            );
          },
          error: (err) => subject.error(err),
          complete: () => subject.complete(),
        });

      subject.subscribe(console.log);
```

I have played around with it for a bit but can't seem to figure out the exact cause. My guess is either (a) `lastSnapshot` isn't being set OR (b) the current snapshot and lastSnapshot are always in sync, or at least at the time when `docChanges()` runs from within a `onSnapshot()`

Again thank you so much for your work. Let me know if you need any more information or have any work arounds.

**Comment by gustavohenke** [comment]
Hey! I'm surprised to see someone else using this largely undocumented code 🙂 
I'm glad that you've been able to find your way around the codebase.

The tests for `QuerySnapshot` are doing everything upside down:
https://github.com/gustavohenke/mockbase/blob/e271ba2304d24133a677a0bd459df222d1b4edac/firestore/query-snapshot.test.ts#L95-L119

I must have understood [the docs](https://firebase.google.com/docs/reference/js/firebase.firestore.QuerySnapshot#docchanges) as "since the last emitted snapshot" instead of "since the previous snapshot":

> Returns an array of the documents changes since the last snapshot. If this is the first snapshot, all documents will be in the list as added changes.

Let's see if it's a fast fix.

**Comment by gustavohenke** [comment]
I've published v0.5.1 with a fix for this.
Let me know how it goes!

**Comment by wSedlacek** [comment]
Thank you for the quick reply! I have been testing v0.5.1 but I still don't seem to be getting the `removed`.

I have create a reproduction Code Sandbox.
https://codesandbox.io/s/clever-zhukovsky-o0h9v?file=/src/index.js

I expect to have console.log of `Added Item` which I get, followed by `Modified Item` which also works then I expect to have a console.log of `Removed Item` which I don't get.

**Comment by gustavohenke** [comment]
Coolio! v0.5.2 seems to have finally nailed it: https://codesandbox.io/s/vigilant-bas-fkpur?file=/src/index.js

Try it yourself and let me know how it goes.

**Comment by wSedlacek** [comment]
Fantastic! Thank you for all your hard work! We are getting much closer!
There was one more inconsistently I found with this latest patch.

If there are two items, and you delete the first one you get a `modified` rather then a `removed`

Example:
https://codesandbox.io/s/recursing-johnson-b6kl1?file=/src/index.js
